# Generated by Django 5.2.7 on 2025-10-25 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Date_created',
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
