# Generated by Django 5.2.7 on 2025-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.CharField(max_length=20),
        ),
    ]
