# Generated by Django 5.2.7 on 2025-11-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
